//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HeavyTransportation.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string DeparturePoint { get; set; }
        public string DestinationPoint { get; set; }
        public int DistanceKM { get; set; }
        public int WeightKG { get; set; }
        public int IdDriver { get; set; }
        public Nullable<int> IdParthner { get; set; }
        public int IdTrailer { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual Driver Driver1 { get; set; }
        public virtual Trailer Trailer { get; set; }
    }
}
